//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _CLOZEMOODLEGENERATOR_CLOZEMOODLEGENERATOR_WXCRAFTER_BASE_CLASSES_H
#define _CLOZEMOODLEGENERATOR_CLOZEMOODLEGENERATOR_WXCRAFTER_BASE_CLASSES_H

// clang-format off
#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/ribbon/bar.h>
#include <wx/ribbon/art.h>
#include <wx/ribbon/page.h>
#include <wx/ribbon/panel.h>
#include <wx/ribbon/buttonbar.h>
#include <wx/panel.h>
#include <wx/notebook.h>
#include <wx/imaglist.h>
#include <wx/stc/stc.h>
#include <wx/webview.h>
#include <wx/grid.h>
#include <wx/richtext/richtextctrl.h>
#include <wx/menu.h>
#include <wx/dialog.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/button.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif

// clang-format on

class MainFrameBaseClass : public wxFrame
{
protected:
    wxRibbonBar* m_ribbonBarMain;
    wxRibbonPage* m_ribbonPageMain;
    wxRibbonPanel* m_ribbonPanelFile;
    wxRibbonButtonBar* m_ribbonButtonBarFile;
    wxRibbonPanel* m_ribbonPanelTools;
    wxRibbonButtonBar* m_ribbonButtonBarTools;
    wxRibbonPanel* m_ribbonPanelHelp;
    wxRibbonButtonBar* m_ribbonButtonBarHelp;
    wxPanel* m_mainPanel;
    wxNotebook* m_notebookMain;
    wxPanel* m_panelHTML;
    wxStyledTextCtrl* m_stcHTML;
    wxPanel* m_panelPreview;
#if wxUSE_WEBVIEW
    wxWebView* m_webViewPreview;
#endif // wxUSE_WEBVIEW

    wxStyledTextCtrl* m_stcPython;
    wxGrid* m_gridInputs;
    wxRichTextCtrl* m_richTextCtrlConsole;
    wxMenuBar* m_menuBar;
    wxMenu* m_nameFile;
    wxMenuItem* m_menuItemNew;
    wxMenuItem* m_menuItemSave;
    wxMenuItem* m_menuItemSaveAs;
    wxMenuItem* m_menuItemOpen;
    wxMenuItem* m_menuItemExport;
    wxMenuItem* m_menuItemExit;
    wxMenu* m_nameHelp;
    wxMenuItem* m_menuItemAbout;

protected:
    virtual void OnWindowClose(wxCloseEvent& event)
    {
        event.Skip();
    }
    virtual void OnSaveRibbonClick(wxRibbonButtonBarEvent& event)
    {
        event.Skip();
    }
    virtual void OnSaveAsRibbonClick(wxRibbonButtonBarEvent& event)
    {
        event.Skip();
    }
    virtual void OnOpenRibbonClick(wxRibbonButtonBarEvent& event)
    {
        event.Skip();
    }
    virtual void OnExportRibbonClick(wxRibbonButtonBarEvent& event)
    {
        event.Skip();
    }
    virtual void OnQuitRibbonClick(wxRibbonButtonBarEvent& event)
    {
        event.Skip();
    }
    virtual void OnGetInputRibbonClick(wxRibbonButtonBarEvent& event)
    {
        event.Skip();
    }
    virtual void OnRunPyRibbonClick(wxRibbonButtonBarEvent& event)
    {
        event.Skip();
    }
    virtual void OnPreviewRibbonClick(wxRibbonButtonBarEvent& event)
    {
        event.Skip();
    }
    virtual void OAboutRibbonClick(wxRibbonButtonBarEvent& event)
    {
        event.Skip();
    }
    virtual void OnIndicatorClick(wxStyledTextEvent& event)
    {
        event.Skip();
    }
    virtual void OnMarginClick(wxStyledTextEvent& event)
    {
        event.Skip();
    }
#if wxUSE_WEBVIEW
#endif // wxUSE_WEBVIEW
    virtual void OnCellDataChanged(wxGridEvent& event)
    {
        event.Skip();
    }
    virtual void OnLeftClick(wxGridEvent& event)
    {
        event.Skip();
    }
    virtual void OnNewClick(wxCommandEvent& event)
    {
        event.Skip();
    }
    virtual void OnSaveClick(wxCommandEvent& event)
    {
        event.Skip();
    }
    virtual void OnSaveAsClick(wxCommandEvent& event)
    {
        event.Skip();
    }
    virtual void OnOpenClick(wxCommandEvent& event)
    {
        event.Skip();
    }
    virtual void OnExportClick(wxCommandEvent& event)
    {
        event.Skip();
    }
    virtual void OnExit(wxCommandEvent& event)
    {
        event.Skip();
    }
    virtual void OnAbout(wxCommandEvent& event)
    {
        event.Skip();
    }

public:
    wxRibbonBar* GetRibbonBarMain()
    {
        return m_ribbonBarMain;
    }
    wxStyledTextCtrl* GetStcHTML()
    {
        return m_stcHTML;
    }
    wxPanel* GetPanelHTML()
    {
        return m_panelHTML;
    }
    wxWebView* GetWebViewPreview()
    {
        return m_webViewPreview;
    }
    wxPanel* GetPanelPreview()
    {
        return m_panelPreview;
    }
    wxNotebook* GetNotebookMain()
    {
        return m_notebookMain;
    }
    wxStyledTextCtrl* GetStcPython()
    {
        return m_stcPython;
    }
    wxGrid* GetGridInputs()
    {
        return m_gridInputs;
    }
    wxRichTextCtrl* GetRichTextCtrlConsole()
    {
        return m_richTextCtrlConsole;
    }
    wxPanel* GetMainPanel()
    {
        return m_mainPanel;
    }
    wxMenuBar* GetMenuBar()
    {
        return m_menuBar;
    }
    MainFrameBaseClass(wxWindow* parent,
        wxWindowID id = wxID_ANY,
        const wxString& title = wxT("Cloze generator"),
        const wxPoint& pos = wxDefaultPosition,
        const wxSize& size = wxSize(1280, 720),
        long style = wxCAPTION | wxRESIZE_BORDER | wxMAXIMIZE_BOX | wxMINIMIZE_BOX | wxSYSTEM_MENU | wxCLOSE_BOX);
    virtual ~MainFrameBaseClass();
};

class HTMLPreviewBase : public wxFrame
{
protected:
#if wxUSE_WEBVIEW
    wxWebView* m_webView;
#endif // wxUSE_WEBVIEW

protected:
#if wxUSE_WEBVIEW
#endif // wxUSE_WEBVIEW

public:
    wxWebView* GetWebView()
    {
        return m_webView;
    }
    HTMLPreviewBase(wxWindow* parent,
        wxWindowID id = wxID_ANY,
        const wxString& title = wxT("Preview"),
        const wxPoint& pos = wxDefaultPosition,
        const wxSize& size = wxSize(800, 600),
        long style = wxDEFAULT_FRAME_STYLE);
    virtual ~HTMLPreviewBase();
};

class ExportCloseBase : public wxDialog
{
protected:
    wxStaticText* m_staticTextCatName;
    wxTextCtrl* m_textCtrlCatName;
    wxStaticText* m_staticTextNumQuiz;
    wxTextCtrl* m_textCtrlNumQuiz;
    wxButton* m_buttonExportar;
    wxButton* m_buttonCancel;

protected:
    virtual void OnExportClick(wxCommandEvent& event)
    {
        event.Skip();
    }
    virtual void OnCancelClick(wxCommandEvent& event)
    {
        event.Skip();
    }

public:
    wxStaticText* GetStaticTextCatName()
    {
        return m_staticTextCatName;
    }
    wxTextCtrl* GetTextCtrlCatName()
    {
        return m_textCtrlCatName;
    }
    wxStaticText* GetStaticTextNumQuiz()
    {
        return m_staticTextNumQuiz;
    }
    wxTextCtrl* GetTextCtrlNumQuiz()
    {
        return m_textCtrlNumQuiz;
    }
    wxButton* GetButtonExportar()
    {
        return m_buttonExportar;
    }
    wxButton* GetButtonCancel()
    {
        return m_buttonCancel;
    }
    ExportCloseBase(wxWindow* parent,
        wxWindowID id = wxID_ANY,
        const wxString& title = wxT("Exportar questões"),
        const wxPoint& pos = wxDefaultPosition,
        const wxSize& size = wxSize(500, 300),
        long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~ExportCloseBase();
};

#endif
